<?php

/**
 * @file
 * Contains forum_access.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;
use Symfony\Component\Routing\Route;

require_once __DIR__ . '/includes/forum_access.acl.inc';
require_once __DIR__ . '/includes/forum_access.admin.inc';
require_once __DIR__ . '/includes/forum_access.common.inc';
require_once __DIR__ . '/includes/forum_access.node.inc';
require_once __DIR__ . '/includes/forum_access.theme.inc';

/**
 * Implements hook_help().
 */
function forum_access_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the forum_access module.
    case 'help.page.forum_access':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Allows forums to be set private and to be given moderators.') . '</p>';

      $router = \Drupal::service('router.no_access_checks');
      $result = $router->match('/forum');
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function forum_access_theme($existing, $type, $theme, $path) {
  $result['forum_access_table'] = array(
    'render element' => 'form',
  );

  return $result;
}
