<?php

/**
 * @file
 * Contains forum_access.module..
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function forum_access_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the forum_access module.
    case 'help.page.forum_access':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Allows forums to be set private and to be given moderators.') . '</p>';
      return $output;

    default:
  }
}
